"""ORM schema for the mock social platform (architecture doc section 5).

Five tables, exactly as specified:
    Channel          a channel + its character_profile_json blob of simulation modifiers
    Post             a published post (content + channel + simulated publish time)
    Metric           one engagement snapshot per post per simulate-tick (append-only)
    Comment          simulated comment text (what the Community Manager reads)
    SimulationState  per-campaign simulated clock + recent format history (novelty decay)

Notes:
- Ids are strings (uuid4 hex generated by the API layer) — readable in the
  trace log and stable across DB resets.
- `hashtags_json`/`format_history_json`/`character_profile_json` are JSON text
  columns: SQLite has no array type, and the shapes are small and fixed.
- Timezone-aware UTC datetimes are stored via ISO strings (aiosqlite returns
  strings; the API layer parses them back into aware datetimes).
"""

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, Integer, JSON, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from platform.db import Base


def _now_utc() -> datetime:
    return datetime.now(timezone.utc)


def as_utc(dt: datetime) -> datetime:
    """Re-attach UTC on datetimes read back from SQLite.

    SQLite's DateTime storage keeps the UTC *components* but drops tzinfo on
    the way out (aiosqlite returns naive datetimes). Every API-layer read goes
    through this so outbound data is always timezone-aware.
    """
    return dt.replace(tzinfo=timezone.utc) if dt.tzinfo is None else dt


class Channel(Base):
    """A social channel with its simulated audience character."""

    __tablename__ = "channels"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    name: Mapped[str] = mapped_column(String(120), unique=True)
    type: Mapped[str] = mapped_column(String(32))  # shortform_video | discussion | professional
    # JSON blob the simulation engine reads: length penalty, peak hours,
    # hashtag sweet spot, tone, audience. See platform/db.py::_seed_channels.
    character_profile_json: Mapped[str] = mapped_column(Text)


class Post(Base):
    """A post published to a channel on the mock platform."""

    __tablename__ = "posts"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    campaign_id: Mapped[str] = mapped_column(String(64), index=True)
    channel_id: Mapped[str] = mapped_column(String(64), index=True)
    copy: Mapped[str] = mapped_column(Text)
    # list[str], canonical "#tag" form; JSON column => store/parse handled by SQLAlchemy
    hashtags_json: Mapped[list] = mapped_column(JSON)
    cta: Mapped[str | None] = mapped_column(Text, nullable=True)
    # creative asset type of the post (image/video/carousel/text_only) — the
    # novelty-decay rule groups on this per channel per day
    format: Mapped[str] = mapped_column(String(32), default="text_only")
    # Simulated publish time (may be backdated/forward-dated by the scheduler;
    # NOT necessarily wall-clock now)
    published_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)


class Metric(Base):
    """One engagement snapshot for one post. Append-only per simulate-tick.

    Cumulative counters since publish (impressions, likes, ...) plus the
    window's follower delta. The analytics endpoint aggregates the latest row
    per post; keeping history lets the Analytics Agent see growth curves.
    """

    __tablename__ = "metrics"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    post_id: Mapped[str] = mapped_column(String(64), index=True)
    impressions: Mapped[int] = mapped_column(Integer, default=0)
    likes: Mapped[int] = mapped_column(Integer, default=0)
    comments: Mapped[int] = mapped_column(Integer, default=0)
    shares: Mapped[int] = mapped_column(Integer, default=0)
    saves: Mapped[int] = mapped_column(Integer, default=0)
    clicks: Mapped[int] = mapped_column(Integer, default=0)
    follower_delta: Mapped[int] = mapped_column(Integer, default=0)
    recorded_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)


class Comment(Base):
    """A simulated comment on a post (real text, not just a count)."""

    __tablename__ = "comments"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    post_id: Mapped[str] = mapped_column(String(64), index=True)
    author_handle: Mapped[str] = mapped_column(String(64))
    text: Mapped[str] = mapped_column(Text)
    sentiment: Mapped[str] = mapped_column(String(16))  # positive | neutral | negative
    # Sensitivity pre-filter result (price complaints, competitor mentions...):
    # the Community Manager escalates these instead of auto-replying.
    is_sensitive: Mapped[bool] = mapped_column(Boolean, default=False)
    replied: Mapped[bool] = mapped_column(Boolean, default=False)


class SimulationState(Base):
    """Per-campaign simulated clock + format history for novelty decay.

    One row per campaign_id. `format_history_json` maps
    channel_id -> list of {"date": "YYYY-MM-DD", "format": "video"} entries
    that the novelty-decay rule inspects for "same format 3+ days running".
    """

    __tablename__ = "simulation_state"

    campaign_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    # The simulated wall clock; /simulate/tick advances it.
    current_sim_time: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)
    # dict channel_id -> [{"date": ..., "format": ...}]; JSON defaults must be
    # callables (default=dict), not literals, or SQLAlchemy inserts the literal.
    format_history_json: Mapped[dict] = mapped_column(JSON, default=dict)
    # Latest multipliers per post, kept for observability/debugging.
    last_multipliers_json: Mapped[dict] = mapped_column(JSON, default=dict)


class MessageBusRecord(Base):
    """Durable log of every agent-to-agent message (Day 2, doc section 7).

    Append-only by convention: the API never updates or deletes rows — the
    agent conversation must survive a restart and be replayable for the
    write-up. Mirrored to logs/agent_trace.jsonl by the bus for the
    human-readable trace; SQLite is the source of truth.

    `seq` (autoincrement) is the global order; `message_id` is the stable uuid
    used by bus consumers. `campaign_id` is indexed because every read path
    (history(campaign_id)) filters on it.
    """

    __tablename__ = "message_bus"

    seq: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    message_id: Mapped[str] = mapped_column(String(64), unique=True)
    timestamp: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)
    from_agent: Mapped[str] = mapped_column(String(64))
    to_agent: Mapped[str] = mapped_column(String(64), index=True)
    campaign_id: Mapped[str] = mapped_column(String(64), index=True)
    message_type: Mapped[str] = mapped_column(String(64))
    payload_json: Mapped[dict] = mapped_column(JSON)


class NeedsHumanReview(Base):
    """Escalation queue: sensitive community comments routed to a human (Day 3).

    The Community Manager's contract (architecture doc section 7): comments
    flagged sensitive by the platform, or mis-classified by the router, are
    NOT auto-replied — they land here for a human decision. A real product
    would render this as a review UI; the mock keeps it as a table + the CLI
    `queue` viewer. Pages through the same SQLite DB as everything else.
    """

    __tablename__ = "needs_human_review"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    campaign_id: Mapped[str] = mapped_column(String(64), index=True)
    post_id: Mapped[str] = mapped_column(String(64), index=True)
    comment_id: Mapped[str] = mapped_column(String(64))
    reason: Mapped[str] = mapped_column(Text)
    comment_text: Mapped[str] = mapped_column(Text, default="")
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)
    resolved: Mapped[int] = mapped_column(Integer, default=0)  # 0 = open, 1 = done


class MemoryRecord(Base):
    """One stored embeddable learning from a prior campaign (Day 3, doc section 10).

    The memory layer (memory/campaign_memory.py) stores a WeeklyReport's
    recommendations + patterns_found as a text blob with a local embedding
    vector (pure-Python, offline/deterministic); the Strategy Agent retrieves
    the top-k most cosine-similar records when planning the next campaign.

    `vector_json` is a fixed-dimension list of floats (JSON text column —
    SQLite has no array type).
    """

    __tablename__ = "memory_records"

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    campaign_id: Mapped[str] = mapped_column(String(64), index=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now_utc)
    source_week: Mapped[int] = mapped_column(Integer, default=1)
    # Human-readable learning text (what retrieval returns to the Strategy Agent).
    text: Mapped[str] = mapped_column(Text)
    vector_json: Mapped[dict] = mapped_column(JSON, default=dict)  # {"vector": [...]}
